- id: rails-migration
  additional_dependencies: ['git']
  description: Check if the migration file corresponding to schema.rb has been committed
  entry: rails-migration-validate.rb
  files: db/schema.rb
  language: ruby
  name: Validate db/schema.rb and migration files
