#!/usr/bin/env ruby
# frozen_string_literal: true

current_dir = File.dirname(__FILE__)
lib_path = File.expand_path("../lib", current_dir)
$LOAD_PATH.unshift(lib_path)

require "pre_commit_fake_gem"
require "open3"

EXIT_SUCCESS = 0
EXIT_FAILURE = 1
EXIT_UNSUPPORTED_FILE = 2
EXIT_NOT_FOUND_VERSION = 3

begin
  PreCommitFakeGem::MissingMigrationFileService.new(ARGV).execute
  exit(EXIT_SUCCESS)
rescue PreCommitFakeGem::MissingMigrationFileService::GitUncontrolledFileError
  exit(EXIT_FAILURE)
rescue PreCommitFakeGem::MissingMigrationFileService::NotSupportedFileError
  warn "This script only works with db/schema.rb"
  exit(EXIT_UNSUPPORTED_FILE)
rescue PreCommitFakeGem::MissingMigrationFileService::NotFoundMigrationVersion
  warn "Could not find migration version in db/schema.rb"
  exit(EXIT_NOT_FOUND_VERSION)
end
